FROM tensorflow/tensorflow-gpu:1.15.5-py3

COPY requirements.txt /root/requirements.txt
RUN apt update && apt install -y libsndfile1 libsndfile-dev ffmpeg && pip3 install -r /root/requirements.txt

CMD /bin/bash